DROP SCHEMA IF EXISTS employee CASCADE;
CREATE SCHEMA employee;

CREATE TABLE employee.member (
  id   INTEGER PRIMARY KEY,
  name VARCHAR(40) NOT NULL,
  phone VARCHAR(13) NOT NULL,
  mail VARCHAR(255) NOT NULL,
  last_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE SEQUENCE employee.id;


CREATE TABLE employee.status (
  category VARCHAR(40) PRIMARY KEY,
  count  INTEGER NOT NULL,
  last_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);


